#!/usr/bin/env python3
"""Generate include/RED4ext/Memory/PoolSymbols.hpp from the macOS game binary.

The macOS build exports red::memory::PoolStorageProxy<Pool>::{Allocate, Free, ...} for every memory pool. This
maps each pool named in Memory/Pools.hpp to the mangled template argument of its proxy, so the SDK can reach the
game's allocators through dlsym instead of reverse-engineered addresses. Re-run after a game update.

Usage: gen_pool_symbols.py [--binary PATH]
"""

import argparse
import re
import subprocess
from pathlib import Path

from validate_addresses import DEFAULT_BINARY

ROOT = Path(__file__).resolve().parent.parent
POOLS = ROOT / "include/RED4ext/Memory/Pools.hpp"
OUT = ROOT / "include/RED4ext/Memory/PoolSymbols.hpp"
PROXY = re.compile(r"^__ZN3red6memory16PoolStorageProxyI(N\w+?E)E8AllocateEy$")


def last_component(arg: str) -> str:
    """Unqualified name from a mangled nested name such as N5input17PoolInputInternalE or NS_11PoolDefaultE."""
    i, name = 1, ""
    while i < len(arg) - 1:
        if arg[i] == "S":  # substitution: S_ or S<n>_
            i = arg.index("_", i) + 1
        elif arg[i].isdigit():
            j = i
            while arg[j].isdigit():
                j += 1
            n = int(arg[i:j])
            name, i = arg[j : j + n], j + n
        else:
            break
    return name


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--binary", type=Path, default=DEFAULT_BINARY)
    args = ap.parse_args()

    nm = subprocess.run(["nm", "-gU", "-j", str(args.binary)], capture_output=True, text=True, check=True).stdout
    by_name = {}
    for sym in nm.split():
        m = PROXY.match(sym)
        if m:
            arg = m.group(1)
            by_name.setdefault(last_component(arg), arg)

    sdk_pools = re.findall(r'static constexpr auto Name = "(\w+)";', POOLS.read_text())
    rows, missing = [], []
    for name in sdk_pools:
        if name in by_name:
            rows.append(f'    {{"{name}", "{by_name[name]}"}},')
        else:
            missing.append(name)

    OUT.write_text(
        "#pragma once\n\n"
        "// Generated by scripts/gen_pool_symbols.py from the macOS game binary. Do not edit.\n"
        "// Maps a pool name from Pools.hpp to the mangled template argument of the game's exported\n"
        "// red::memory::PoolStorageProxy<Pool> (symbol: _ZN3red6memory16PoolStorageProxyI<arg>E<method>).\n"
        f"// Pools without an exported proxy: {', '.join(missing) or 'none'}.\n\n"
        "#include <string_view>\n\n"
        "namespace RED4ext::Detail\n{\n"
        "struct PoolSymbol\n{\n    std::string_view name;\n    std::string_view mangledArg;\n};\n\n"
        "inline constexpr PoolSymbol PoolSymbols[] = {\n" + "\n".join(rows) + "\n};\n"
        "} // namespace RED4ext::Detail\n"
    )
    print(f"{OUT.relative_to(ROOT)}: {len(rows)} pools, {len(missing)} without an exported proxy: {missing}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
